### ISSUE TITLE
Adjust screen

### ISSUE THREAD

**Issue by Narsku** [gopaldhola99/sticker_view#7]
Hello!(Sorry for bad english), im currently using your library in a flutter project, and i need to use the entire screen for the stickers but theres a blank container at the bottom, can i force the StickerView widget to use the entire screen?

**Comment by gopaldhola99** [comment]
Hi @Narsku,

Sorry for the late reply!

You can actually set the width and height of StickerView as per your requirement. Parameters for width and height are already there in StickerView widget
